services:
  db:
    image: mongo:6.0
    container_name: db
    networks:
      - pokemon_network
    volumes:
      # Le fichier JSON est monté en lecture seule
      - ./data/pokemon.json:/docker-entrypoint-initdb.d/pokemon.json:ro
      # Le script d'initialisation est monté sans read-only pour permettre le chmod
      - ./data/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "27018:27017"
    # On rend le script exécutable et on lance MongoDB
    command: >
      bash -c "chmod +x /docker-entrypoint-initdb.d/mongo-init.sh && docker-entrypoint.sh mongod"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --host localhost --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./pokemon-tournament
      dockerfile: Dockerfile
    container_name: pokemon-app
    networks:
      - pokemon_network
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

networks:
  pokemon_network:
    driver: bridge
